### ISSUE TITLE
RequireQualifiedAccess on JavaScript.Kind

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#129]
From Don:

JavaScript.Kind should probably be marked RequireQualifiedAccess. 

1. My guess is that the union cases Kind.Object etc. aren’t used that often

2. Client code will be clearer if it uses “Kind.Object” etc. in pattern matching

3. Intellisense menus will be simpler if “Object” etc. are not present at “JavaScript.”, I found them confusing
 

----------------------------------------
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/129
- Originally reported by: Anton Tayanovskyy
- Originally created at: 2013-06-21T16:53:35.127

**Comment by Tarmil** [comment]
It's now under the RequireQualifiedAccess `JS`, so this is not a problem anymore.
