### ISSUE TITLE
Cannot return Map type from Remote call (cannot encode return type to JSON)

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#132]
it doesn't seem possible to return maps over RPC. For example:

```
#!fsharp

  [<Remote>]
  let Foo() = Map.empty<int,int>
```

Causes a compilation error: Cannot encode the return type to JSON.

----------------------------------------
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/132
- Originally reported by: [perfectshuffle](http://bitbucket.org/perfectshuffle)
- Originally created at: 2013-07-06T20:13:55.903

**Comment by Tarmil** [comment]
It has been implemented.
