### ISSUE TITLE
Issues with tuple-domain functions

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#147]
In various parts of WebSharper, Functions of the form `A * B * ... -> C` are assumed to be runtime objects that support both calling conventions:

1. call with a tuple `f(x)` where `x` is an object `{0: A; 1: B; ..}`
2. call with multiple arguments `f(x, y, z)` where `x: A; y: B`, etc

When WebSharper produces function values with tuple domain, it makes sure they can support both. However, the second convention is what is usually meant exclusively when assigning `A * B -> C` types to functions at the FFI boundary (`Inline` or `Stub`). There are therefore situations where this breaks down. For example:

```
function GetAdder() {
  return function (x, y) {
    return x + y;
  }
}

```

Suppose this is bound with:

```
[<Inline "GetAdder()">]
let GetAdder () : (int * int -> int) = X<_>
```

Attempting to use it gives an error:

```
let adder = GetAdder ()
adder (1, 2) = 3
```

Since adder is passed the tuple using convention no. 1, but expects convention no. 2.

----------------------------------------
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/147
- Originally reported by: Anton Tayanovskyy
- Originally created at: 2013-09-04T21:06:38.938

**Comment by Tarmil** [comment]
This is now explicit with `FuncWithArgs` and friends, and automatically managed in WIG.
