### ISSUE TITLE
Put the DOM event in the Event argument passed by On* functions

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#174]
To allow for example:

``` fsharp
A [Attr.HRef "#"; Text "Do something"]
|>! OnClick (fun _ ev ->
    doSomething()
    ev.Event.PreventDefault() // Don't go to '#'
)
```

Right now the only way to do this is to use `AddEventHandler` or `JQuery.On` inside `OnAfterRender`, instead of `OnClick`.

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/174
- Originally reported by: Loic Denuziere
- Originally created at: 2013-10-17T11:33:44.338

**Comment by Tarmil** [comment]
This is a simple change for keyboard and mouse events, but it is a breaking change for other events because we currently don't pass anything, so the callback type would change from `'T -> unit` to `'T -> SomeEventType -> unit`.
