### ISSUE TITLE
Restore "Run" target for HTML apps

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#235]
And make sure it works on XS/MD.

----------------------------------------
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/235
- Originally reported by: Anton Tayanovskyy
- Originally created at: 2014-04-15T00:55:10.829

**Comment by Tarmil** [comment]
[Moved to websharper.visualstudio repository.](https://github.com/intellifactory/websharper.visualstudio/issues/1)
