### ISSUE TITLE
WIG doesn't prevent us from creating a duplicate class

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#255]
Example:

```
let C1 = Class "Foo"
let C2 = Class "Foo"

Assembly "Bar" [
    C1
    C2
]
```

This creates two classes with the same name. WIG should probably detect this and throw an error.

----------------------------------------
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/255
- Originally reported by: Rakonczai Sándor
- Originally created at: 2014-06-11T15:36:16.077

**Comment by Tarmil** [comment]
This now throws:

```
error : Duplicate type definition: Bar.Foo
```
