### ISSUE TITLE
Cannot "run" Html Website project in VS

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#258]
Without debugger (Ctrl+F5) - nothing happens. With debugger "cannot debug this project."

----------------------------------------
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/258
- Originally reported by: Anton Tayanovskyy
- Originally created at: 2014-07-03T15:47:14.841

**Comment by Tarmil** [comment]
Duplicate of #235.
