### ISSUE TITLE
Support for Manos de Mano

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#26]
See http://manosdemono.org/

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/26
- Originally reported by: Anton Tayanovskyy
- Originally created at: 2012-02-24T15:37:06.069

**Comment by Tarmil** [comment]
> NOTE: this project is not under active development anymore.

https://github.com/jacksonh/manos
