### ISSUE TITLE
Inconsistency in WIG

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#265]
If I mark a configuration pattern property as required, its name won't be capitalized.

```
#!fsharp
let Resource =
    Pattern.Config "Resource" {
        Required =
            [
                "name", T<string>
            ]
        //...
    }
```

----------------------------------------
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/265
- Originally reported by: Rakonczai Sándor
- Originally created at: 2014-07-22T13:41:07.841

**Comment by Jand42** [comment]
For WebSharper 3.0, `Pattern.Config` keeps old behavior. There is a newer `Pattern.RequiredFields` which generates a read-write property but still the constructor argument is lower-case.
