### ISSUE TITLE
Allow external NuGet packages to be used within WebSharper templates

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#273]
Currently, it seems that only the base W# NuGet package can be included in W# templates, which means that external ones can't be used.

It would be better to allow external packages to be used too, perhaps by adding them into a packages.config so that they can be retrieved by package restore.

Required by #272.

(I'll do this, but can't assign myself)

----------------------------------------
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/273
- Originally reported by: Simon Fowler
- Originally created at: 2014-08-21T13:30:17.654

**Comment by Tarmil** [comment]
This was implemented when creating the Owin template.
