### ISSUE TITLE
SPAs don't extract embedded images and other non-code (<> JS/CSS) artifacts

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#296]
... and special care is needed for making sure that the images, etc referenced via relative paths in CSS are treated correctly.

----------------------------------------
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/296
- Originally reported by: Adam Granicz
- Originally created at: 2014-10-17T16:13:15.741

**Comment by granicz** [comment]
Not sure if there is much we can do about CSS url-ed resources, but we must fix the extracting of these resources finally.

**Comment by Jand42** [comment]
In https://github.com/intellifactory/websharper/commit/9b1041 all web resources are extracted under output path, next to the `.js` and `.css` files (default is `\Content`).
