### ISSUE TITLE
can't install on VS 2015 preview

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#299]
Installer says, that there is no compatible version of visual studio installed, but prerequisites tell 2010 or newer, which 2015 obviously is. 

----------------------------------------
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/299
- Originally reported by: Norbert Melzer
- Originally created at: 2014-11-23T00:03:40.408

**Comment by Jand42** [comment]
Works for me for VS2015 CTP6.
