### ISSUE TITLE
WIG template should not open IntelliFactory.WebSharper

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#303]
This brings in the `?` operator that accesses JavaScript object fields, overriding the `?` from WIG that defines a name for a method argument.

----------------------------------------
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/303
- Originally reported by: Loic Denuziere
- Originally created at: 2014-11-28T20:36:15.780

**Comment by Tarmil** [comment]
This is not problematic anymore.
