### ISSUE TITLE
Create proxy for System.Guid

### ISSUE THREAD

**Issue by endeavour** [intellifactory/websharper#309]
Guids are not really supported on the client side. Would be nice to be able to use guids in rpc calls, to be able to do System.Guid.NewGuid() on the client side, as well as someGuid.ToString()

**Comment by Jand42** [comment]
System.Guid.NewGuid() has client side proxy (Guids are stored as a string in JavaScript) and Guids are usable in Remote functions in the 3.0.15-alpha release.
