### ISSUE TITLE
Url with DateTime is not binding correctly to Action

### ISSUE THREAD

**Issue by kowalgta** [intellifactory/websharper#314]
I have a sitelet that has an action shape with a DateTime value:

    type Action =
         | Test of DateTime

    Sitelet.Infer <| function
        | Test dt -> (...)

The URL to this action is generated correctly: http://localhost:5043/Test/2014-12-19T15:38:20.5096124+00:00

The problem is that if I do a GET request on this URL it will not execute the Test branch. It will, however, if I manually edit URL to be http://localhost:5043/Test/2014-12-19.

I've tested UrlFormatter itself and it seems to be working fine (GetFormatFor reads and shows URL correctly). I suspect it might be something connected with OWIN pipeline.

**Comment by Tarmil** [comment]
The problem is that the character `:` is invalid in the path part of a URI. When I try to do the same with the ASP.NET pipeline, I get a yellow error page with the message:

    A potentially dangerous Request.Path value was detected from the client (:).

So clearly the way we encode DateTime in URIs is wrong; I'm not sure what would be a good format though.

**Comment by kowalgta** [comment]
Personally I would be happy with "yyyyMMddTHHmmss". Some discusson on the topic here: http://stackoverflow.com/questions/2344987/is-there-a-standard-date-time-format-that-can-be-passed-on-a-url

**Comment by Tarmil** [comment]
The default is now "yyyy-MM-dd-HH.mm.ss", and you can use `DateTimeFormatAttribute` to customize it:

```fsharp
type Action =
    | [<DateTimeFormat("date", "yyyy-MM-dd")>] Test of date: DateTime
```
