### ISSUE TITLE
Sitelet.Protect should use Content.RedirectTemporary instead of Content.Redirect

### ISSUE THREAD

**Issue by radekm** [intellifactory/websharper#315]
Firefox 34 caches permanent redirects. So using `Content.Redirect` may cause that user is redirected from protected page even when he is logged in. This doesn't happen in Chrome 39.

**Comment by endeavour** [comment]
I ran into the same issue in Chrome (but only if the developer tools are closed).

**Comment by Tarmil** [comment]
This is indeed an oversight, we will fix it soon.

**Comment by Bananas-Are-Yellow** [comment]
Does this mean that I no longer need to use `RandomizeUrl`, which I've seen in various code examples, including this [SampleSite.fs](https://github.com/intellifactory/websharper/blob/725a439cd3512ed2cad83c603275daddcac9f4d5/tests/WebSharper.Sitelets.Tests/SampleSite.fs#L95) file from the WebSharper tests?

**Comment by Tarmil** [comment]
Yes, that should work correctly.
