### ISSUE TITLE
Non managed dlls in a bin folder are causing a build error

### ISSUE THREAD

**Issue by kowalgta** [intellifactory/websharper#316]
Function Unpack from WebSharperTask.fs assumes that all files in a bin folder with the extension .dll and .exe are managed. Unfortunately if there are any files that are not managed (with the extension .dll or .exe) it is going to end up with an error "Format of the executable (.exe) or library (.dll) is invalid.".

In my particular case SqLite is causing it to break as it comes with SQLite.Interop.dll that is unmanaged. 

I've raised an issue about that previously, but back than I had not realized why this is happening:
http://websharper.com/question/77603/websharper-msbuild-problem

**Comment by Tarmil** [comment]
Fixed in 69911ddf51c4edfe8d4e3077de7819d1e5dc7af8
