### ISSUE TITLE
Latest naming changes - WebSocket.ReadyState

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [intellifactory/websharper#317]
I can't figure out how to convert this test:

    ws.ReadyState = WebSocketReadyState.Open

If I put the cursor over the `ReadyState` property and press F12, it shows:

    namespace IntelliFactory.WebSharper.JavaScript

    open IntelliFactory.WebSharper
    open IntelliFactory.WebSharper.JavaScript

    type WebSocket =
        ...
        member ReadyState : WebSocket.ReadyState
        ...

But that's a cyclic definition, unless there is another WebSocket type or module somewhere?

Looking at this:

https://github.com/intellifactory/websharper/blob/8ebc10b95a2924743c9108a669d51ea8fb25db97/src/stdlib/IntelliFactory.WebSharper.JavaScript/Html5.fs#L1609

I'm guessing that there should be a nested `ReadyState` class, but I can't find it.

**Comment by Tarmil** [comment]
Indeed, there is a name collision between the nested type and the member. I will revert the change that made the type nested.

**Comment by Bananas-Are-Yellow** [comment]
Thank you.
