### ISSUE TITLE
Type extensions won't get inlined properly

### ISSUE THREAD

**Issue by qwe2** [intellifactory/websharper#328]
If you use a type extension the `this` parameter (or with any other name for the matter) will not get expanded and will be inlined as is:

```fsharp
type Dom.Element with
    [<Inline "$this.childNodes">]
    member this.GetChildren() = X<Dom.NodeList>

let Main =
    let elem = ById("entry")
    Console.Log(elem.GetChildren())
```

Here `elem.GetChildren()` will be transformed to `$this.childNodes` instead of `elem.childNodes`.

**Comment by Jand42** [comment]
Extension methods are static methods behind, so it parses the inline like accordingly.
Some scenarios:
```fsharp
    [<Inline "$0.test">]
    member this.TestMethod() = X<int>
````
Works correctly.
```fsharp
    [<Inline "$this.test">]
    member this.TestMethod() = X<int>
````
Fails. It is a curried static method of the "this" argument and a unitVar, but reflection somehow turns up the "this" parameter name as an empty string.
```fsharp
    [<Inline "$this.testf($x)">]
    member this.TestMethod1 (x: int) = X<int[]>
````
Works, but only incidentally. "this" is the name of the first curried parameter, so this fails:
```fsharp
    [<Inline "$this.testf($x)">]
    member o.TestMethod1 (x: int) = X<int[]>
````

**Comment by Jand42** [comment]
Using `$0` always works, and also with normal methods if there is a parameter named `this` then `$this` gets overwritten in the dictionary used by the inline parser. So using `$0` is the only safe choice which should be the recommended.
