### ISSUE TITLE
Manual bindings where fields are keywords

### ISSUE THREAD

**Issue by jabolopes** [intellifactory/websharper#332]
Hi,

I am trying to bind with the CKEditor and the setData method on the editor takes
an options struct which contains a member called "internal". The problem is that
this is a keyword in F#, so the following code is not valid.

type SetDataOptions [<Inline "{}">] () =
      [<DefaultValue>]
      val mutable internal: bool // default is false

Is there a way to fix this? Why is it not possible to use [<Name "internal">] to perform
the mapping in this case?

**Comment by qwe2** [comment]
Hey,

i'm really not familiar with these kind of manual bindings as I never needed to use them, but this seems to compile to the right property:

```fsharp 
[<DefaultValue>]
val mutable ``internal`` : bool
```

I admit it doesn't look great in code, but it seems to work. Alternatively, I suggest that you use [WIG](http://www.websharper.com/docs/wig) for bigger bindings like this (I myself have never used anything else but WIG for JS libraries).

**Comment by Jand42** [comment]
Another option is to use the `Name` attibute, and use some non-keyword for the F# name:

```fsharp
[<Name "internal">]
val mutable Internal: bool
```
