### ISSUE TITLE
RPC async issue on (some) mobile browsers

### ISSUE THREAD

**Issue by malbertife** [intellifactory/websharper#333]
Hi,
Android 4.0, stock browser (not Chrome), WebSharper 3.0.15.92-alpha.
In the "Client-Server Web Application" template project, clicking on the button does not seem to perform the RPC. The Javascript console says:
"[...]/Scripts/WebSharper/IntelliFactory.WebSharper.js:1337
WebSharper: Uncaught asynchronous exception"
The same seems to happen with Internet Explorer on Windows Phone 8.1, but I don't know how to show the Javascript console.
It does work as expected in Chrome on Android 4.0.
Cheers.

**Comment by ca-ta** [comment]
please check out #331 - you might experience the same issue

**Comment by qwe2** [comment]
Which WebSharper version are you using? I have confirmed that RPC is working in `WS 3.0.12.88` but not in `3.0.15.92` in Android stock browser, so something between the two broke it. Seems like it's working again with our newest internal build so it might be the same issue as what @ca-ta mentioned, and has already been fixed but not included in a public build yet.

**Comment by malbertife** [comment]
I was using `WS 3.0.15.92-alpha`.
I confirm that the GitHub master version works, both on Android and Windows Phone.
Thanks for your prompt reply.
