### ISSUE TITLE
Sitelet.Embed may cause deadlock since it uses Async.RunSynchronously

### ISSUE THREAD

**Issue by radekm** [intellifactory/websharper#355]
`Sitelet.Embed` calls `Content.ToResponse` which calls `Async.RunSynchronously`. If the call to `Async.RunSynchronously` happens in the thread with `AspNetSynchronizationContext` and asynchronous action uses `Async.SwitchToContext` to ensure `AspNetSynchronizationContext` then the program deadlocks.

This can be fixed by using `Content.CustomContentAsync` and `Content.ToResponseAsync` in `Sitelet.Embed` instead of `Content.CustomContent` and `Content.ToResponse`.

**Comment by Tarmil** [comment]
Thanks for the catch! I don't know what I was thinking when I wrote this.
