### ISSUE TITLE
JsonAttribute doesn't handle null values correclty with Value Types

### ISSUE THREAD

**Issue by qwe2** [intellifactory/websharper#357]
Suppose I have the following record and `Sitelet` action:

```fsharp
type A = { id : int; date : System.DateTime }

type Action =
    | [<Method "POST"; Json "payload">] JsonData of A
```

If the JSON payload then has a `null` value in place of `date` WebSharper will return 404.

Edit: actually it would be quite interesting if it did handle it when it's not `Nullable`. So if I make it `Nullable` I get a `Exception of type 'IntelliFactory.WebSharper.Sitelets.ActionEncoding+NoFormatError' was thrown.` on the `Sitelet` initialization.

**Comment by Tarmil** [comment]
Now with an `option<'T>` where `'T` doesn't decode `null`, `null` is decoded into `None`.
