### ISSUE TITLE
Sitelet.Infer routing does not support standard REST API design

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [intellifactory/websharper#373]
I want my REST API to be like this:

`/people` - lists all the people
`/people/123` - returns the person with id=123
`/people/123/children` - returns the children of the person with id=123

I don't seem to be able to do this using `Sitelet.Infer`. I can't create two actions with `[<CompiledName "people">]`, one for `/people` and one for `/people/123`, never mind `/people/123/children`.

The example code here:

https://github.com/intellifactory/websharper/blob/a9969ca0be6afeec52646471551b6abb83196eed/tests/WebSharper.Sitelets.Tests/Api.fs

uses `/person?id=123`, but this is not the standard way to do things. If the `id` specifies the person, it should be `/person/123`, since `id` is not optional.

Do I have to write my own router, or is there a better way to do this?

**Comment by Tarmil** [comment]
Indeed there is currently no easy way to have different actions with the same method and same `CompiledName`, so you need to write your own router. We have been looking at possible ways to enable this, although it is tricky to ensure that these actions do not overlap.

**Comment by Bananas-Are-Yellow** [comment]
OK, thanks. Rather than writing a router by hand, my workaround is to put the conflicting cases into separate action unions, and then combine them into an overall union using `Sitelet.EmbedInUnion` and `Sitelet.Sum`. This seems to work.
