### ISSUE TITLE
"This stream does not support seek operations" when doing POST

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [intellifactory/websharper#376]
I'm trying to test out the example code for a REST API:

https://github.com/intellifactory/websharper/blob/a9969ca0be6afeec52646471551b6abb83196eed/tests/WebSharper.Sitelets.Tests/Api.fs#L38

When I do a POST to create a new person, I get a `NotSupportedException` inside the Sitelet code saying _"This stream does not support seek operations"_. It seems to occur in the call to `Request.Body.Length` here:

https://github.com/intellifactory/websharper/blob/master/src/sitelets/WebSharper.Sitelets/ActionEncoding.fs#L556

It happens when I call the API programmically using `HttpClient` and also when I use the Composer pane in Fiddler.

Is this a bug, or am I doing something wrong?

**Comment by Tarmil** [comment]
What version of .NET or Mono are you using?

**Comment by Bananas-Are-Yellow** [comment]
.NET 4.5.1

**Comment by Tarmil** [comment]
Are you using the ASP.NET module or OWIN?

**Comment by Bananas-Are-Yellow** [comment]
OWIN.

**Comment by Tarmil** [comment]
Okay, that is indeed where the bug lies. The stream provided by the ASP.NET module is seekable, but the one from OWIN isn't. That should be easy to fix, the length is only used to initialize the `MemoryStream` to the right size, so when the stream isn't seekable we can just let it grow by itself.

**Comment by Bananas-Are-Yellow** [comment]
Sounds good.

**Comment by Bananas-Are-Yellow** [comment]
Oops. I closed the issue by accident (pressed the wrong button). Not sure how to 'unclose' an issue, but it looks like it will be fixed shortly anyway.

**Comment by Bananas-Are-Yellow** [comment]
Just found the Reopen button.
