### ISSUE TITLE
Google Maps Library MapTypes.fs Interface Generator Bug

### ISSUE THREAD

**Issue by halfAbee** [intellifactory/websharper#390]
Hi,

I've been trying to use google maps' style types, and I believe you have an unwanted line in MapTypes.fs at line 26:

24:  let MapTypeStyler =
25:     Config "MapTypeStyler"
26:     |+> Static [Constructor T<unit>]

If you comment line 26 out and rebuild, clients can use the MapTypeStyler type, otherwise there is a compiler error because of the extra constructor definition.

**Comment by halfAbee** [comment]
Some code that currently fails to compile (fixed above):

[<JavaScript>]
module GoogleMaps =
    open WebSharper.JavaScript
    open WebSharper.Google.Maps

    let vts = new MapTypeStyler()

**Comment by granicz** [comment]
This is a Google Maps issue and thus should be filed in https://github.com/intellifactory/websharper.google.maps

**Comment by halfAbee** [comment]
OK, I shall close this issue here, and reopen it there.
