### ISSUE TITLE
Missing default attribute for Doc.CheckBox

### ISSUE THREAD

**Issue by kowalgta** [intellifactory/websharper#434]
It seems that there should be a default attribute for single CheckBox:
https://github.com/intellifactory/websharper.ui.next/blob/master/WebSharper.UI.Next/Doc.fs

What is now:
```
Attr.Concat [
                yield! attrs
                yield Attr.DynamicProp "checked" chk.View
            ]
```
What should be:
```
Attr.Concat [
                yield! attrs
                yield Attr.Create "type" "checkbox"
                yield Attr.DynamicProp "checked" chk.View
            ]
```

**Comment by qwe2** [comment]
This issue was moved to intellifactory/websharper.ui.next#20
