### ISSUE TITLE
Proper client-side JSON serialization

### ISSUE THREAD

**Issue by granicz** [intellifactory/websharper#440]
We need a client-side object-to-JSON serialization that sitelet endpoints using the `Json` attribute can intercept and interpret properly.  This serialization should be the same that is provided by `JsonContent` in the reverse direction.

**Comment by endeavour** [comment]
This also needs to support deserialization so that the raw json returned from the sitelets can be hydrated into a record.

**Comment by panesofglass** [comment]
What's the goal here? Would this work similarly to [json-home](http://tools.ietf.org/html/draft-nottingham-json-home-03) in providing a client with the available server resources?

**Comment by endeavour** [comment]
The goal here is that if you have a Websharper-hosted REST endpoint, it should be easy to call it from a websharper JS-compiled client.

In particular:
Need to be able to easily serialise a strongly typed object into a piece of JSON that the server will understand. Then call the server (for example, using jQuery).

It should also be possible to deserialize the JSON that the server returns back into a strongly typed F# object.
