### ISSUE TITLE
Minor issue: Protocol missing from jquery qunit links

### ISSUE THREAD

**Issue by psfblair** [intellifactory/websharper#472]
In the generated ``...fsharp.head.js`` for a single-page application, the script tag pointing to jquery starts with ``http://`` but the ones pointing to ``qunit-1.18.0.js`` and ``qunit-1.18.0.css`` begin with ``//`` with no protocol. This causes errors to show up in my console when browsing the html with the ``file:`` protocol.

**Comment by fdcastel** [comment]
I respectfully disagree. Allow me to offer a counterpoint:

**Every external library should be referenced via protocol-relative URLs**.

(you know... bold text wins arguments ;) )


My head.html/.js currently is

```html
<script src="http://code.jquery.com/jquery-1.11.2.min.js" type="text/javascript" charset="UTF-8">

</script><!--[if lte IE 7.0]>
<![endif]-->
<!--[if lte IE 9.0]>
<![endif]-->
<script src="//code.jquery.com/qunit/qunit-1.18.0.js" type="text/javascript" charset="UTF-8">

</script><link type="text/css" rel="stylesheet" href="//code.jquery.com/qunit/qunit-1.18.0.css" />
<!--[if lte IE 9.0]>
<![endif]-->
```

The first line (link to jquery-1.11.2.min.js) would surely cause problems when served by HTTPS, for example. It should be protocol-relative, like the other two references to qunit (.js and .css)

@psfblair I understand you point. OTOH, please note that this would be just ONE of several glitches you would encounter when serving your application via ```file:``` protocol. The "recommended" way is to just serve it from a webserver. I surely can imagine you have you own reasons to not want this and just use the html file directly (been there, done that). But please mind some things would just not work as expected.

@intellifactory That said, **WHY** do we need an unit test library (qunit?) in the generated application?

**Comment by Tarmil** [comment]
I am closin this issue, as the splitting off of WebSharper.Testing means that QUnit is not included anymore.

On the topic of URLs, I agree with @fdcastel: external libraries should be referenced via protocol-relative URLs, and I will look into applying this for the JQuery link. If you need to browse your website via `file:` protocol, you can override the default URL in your application config file as explained [here](http://websharper.com/docs/resources).
