### ISSUE TITLE
Overzealous uncurrying

### ISSUE THREAD

**Issue by yoff** [intellifactory/websharper#479]
The following program
```fsharp
    let test () =
      let add (v:int) m = v + m
      let run func (c:int) (p:int) : int =
        func p c
      let x = add 2 3
      let y = run add 2 3
      x, y
```
crashes because the local function `add` has been un-curried, but the call inside `run` uses the curried version leading to an error: Uncaught TypeError: add(...) is not a function

The complied java script looks like this:
```javascript
test:function()
    {
     var add;
     add=function(v,m)
     {
      return v+m;
     };
     return[add(2,3),(add(3))(2)];
    }
```
where we see the two incompatible ways to call `add`.

While this is a synthetic test case, the problem manifested fairly deeply in our code base and was tricky to isolate.

---
Additions:
Simplifying `add` to not use its arguments yields a slightly different problem:
```fsharp
    let test () =
      let zero (v:int) (m:int) = 0
      let run func (c:int) (p:int) =
        let _:int = func p c
        0
      let _ = zero 0 0
      run zero 0 0
```
translates to
```javascript
   test:function()
    {
     var zero;
     zero=function()
     {
      return 0;
     };
     zero(0,0);
     (zero(0))(0);
     return 0;
    }
```
with error: Uncaught TypeError: zero(...) is not a function

Finally, trying to force a curried version by calling `add` as `(add 2) 3` makes no difference.

**Comment by yoff** [comment]
Forgot to mention the obvious workaround of un-currying the function yourself; in the above case defining `add` as `let add (v:int, m) = v + m`.

**Comment by Jand42** [comment]
Thanks for the report, it was indeed a long standing lurking bug in an optimizer. When the local function uncurrying optimizer was analyzing if a local function is always used with full arguments, it did not go recursively into arguments of a curried application, but this is where a use of the function was "hiding" in this case.

A release containing the fix for this will be coming today.

**Comment by yoff** [comment]
Thanks for the quick response, that is exactly what I speculated was happening.
