### ISSUE TITLE
Server-side require

### ISSUE THREAD

**Issue by qwe2** [intellifactory/websharper#498]
RequireAttribute only works when including client-side code. It would be nice to have something similar on the server-side too when I don't have an explicit client-side control but just want to include resources.

**Comment by JorgeVV** [comment]
@Tarmil Example of this? Don't know what to do with the Web.Require<'resourceT> instance.

**Comment by Tarmil** [comment]
@JorgeVV Indeed, that is the way to go. I added a section about it in [the documentation](http://developers.websharper.com/docs/resources).
