### ISSUE TITLE
[Question] Inserting JavaScript code without using `ClientSide`

### ISSUE THREAD

**Issue by eggapauli** [intellifactory/websharper#499]
The docs only talk about inserting client-side controls, i.e. controls that are added to the DOM using JavaScript and typically have some JavaScript event handlers attached.  
Is it possible to e.g. `alert` something without creating a client-side control?

**Comment by qwe2** [comment]
Sorry for the delayed answer. AFAIK this is not possible, a client-side control is needed to insert client functionality into a page generated on the server-side. What you can do (and we usually do) is to return an empty document and then nothing will be inserted into the DOM but your side-effecting function will still be called.

Using UI.Next:

```fsharp
open WebSharper
open WebSharper.Sitelets

[<JavaScript>]
module Client =
    open WebSharper.UI.Next
    open WebSharper.JavaScript

    let Main() =
        JS.Alert("Hello!")
        Doc.Empty

module Server =
    open WebSharper.UI.Next

    [<Website>]
    let Main =
        Application.SinglePage(fun ctx ->
            Content.Page(Body = [Doc.ClientSide <@ Client.Main() @>]))
```

**Comment by eggapauli** [comment]
No problem, thanks for the answer.
I got confused by `Doc.ClientSide` returning a `Web.InlineControl` which doesn't play nicely with other `Web.INode` implementations without casting, so I always added an extra `Span [ ClientSide <@ ... @> ]`. Thanks for clarification.
