### ISSUE TITLE
Missing `Window.AddEventListener`

### ISSUE THREAD

**Issue by eggapauli** [intellifactory/websharper#503]
Is there a reason why `JS.Window` doesn't have method `AddEventListener`?

**Comment by Tarmil** [comment]
This is indeed an oversight. I think we should review our binding of the DOM API in general, I know there are a few other things missing such as the `querySelector` family of methods.

**Comment by eggapauli** [comment]
Yep, I also saw that. No problem. The WIG makes it pretty easy to add this. Feel free to close this if you want to.

**Comment by eggapauli** [comment]
Woah cool, that was fast :)
