### ISSUE TITLE
Scripts folder not found on AppHarbor

### ISSUE THREAD

**Issue by FrankBro** [intellifactory/websharper#506]
I found this old issue related: http://www.websharper.com/question/78306/web-targets-for-building-scripts-do-not-work-in-some-environments?page=13
To get my site working on AppHarbor, I need to check in the Scripts folder. I tried looking into the web targets file but I do not see a mention of the Scripts folder. 

For now I have checked in the folder but would love a better solution.

**Comment by Tarmil** [comment]
Yes I can reproduce this issue, and I can see this in the build log:

```
error : Could not find a part of the path 'D:\temp\rlscugrc.ucb\input\test-appharbor\bin'.
```

And indeed, according to earlier log, the binaly output folder is `D:\temp\rlscugrc.ucb\output\_PublishedWebsites\test-appharbor\bin`. So it seems that WebSharper doesn't get the correct output folder. I'm investigating further.

**Comment by Tarmil** [comment]
Okay, so it turns out that AppHarbor uses `OutDir` to define the output directory, rather than `OutputPath` which WebSharper recognizes. I'll fix this shortly and it should be in the next NuGet release. In the meantime, you can work around the issue by putting the following into your project file:

```xml
  <Target Name="SetOutputPathForAppHarbor" BeforeTargets="Build">
    <PropertyGroup>
      <OutputPath Condition="'$(OutDir)' != ''">$(OutDir)</OutputPath>
    </PropertyGroup>
  </Target>
```
