### ISSUE TITLE
Serialization problem with recursive types

### ISSUE THREAD

**Issue by FilippoPolo** [intellifactory/websharper#509]
[< NamedUnionCases>]
type testType =
 | Float of float
 | Prod of testType * testType
let runTest() =
  let v = testType.Prod(testType.Float(1.), testType.Float(0.94))
  let str = WebSharper.Json.Serialize v
  let (v2:Value.t) = WebSharper.Json.Deserialize str
  ignore

In WebSharper, the code above throws a JS exception "expected object".

**Comment by Tarmil** [comment]
Yes, I can reproduce. Looking at the generated JavaScript, I think there is some overly aggressive optimization in the Serialize macro.
