### ISSUE TITLE
More serialization problems with recursive types

### ISSUE THREAD

**Issue by FilippoPolo** [intellifactory/websharper#511]
This is the same repro as #509. After the fix, it still fails, but with a different error.

```fsharp
[< NamedUnionCases>]
type testType =
| Float of float
| Prod of testType * testType

let runTest() =
    let v = testType.Prod(testType.Float(1.), testType.Float(0.94))
    let str = WebSharper.Json.Serialize v
    let (v2:Value.t) = WebSharper.Json.Deserialize str
    ignore
```
In WebSharper, this results in an error "`Cannot read property '1' of undefined`".

**Comment by Tarmil** [comment]
That is strange, your code is working correctly for me with a locally built WebSharper on the current master.

**Comment by granicz** [comment]
We should release the current state unless there are blocking issues elsewhere.

**Comment by FilippoPolo** [comment]
There was a problem on my side; after fixing it, it works. Thanks!
