### ISSUE TITLE
(feature) Add serialization support for string dictionaries

### ISSUE THREAD

**Issue by FilippoPolo** [intellifactory/websharper#513]
String Dictionary is a type we use rather frequently. And JavaScript objects are basically the same thing. So, it would be really nice if the serializer generators supported turning a String Dictionary into a JSON object that has a field for each Dictionary key, with the same name as the key, and the same value as the value.

**Comment by Tarmil** [comment]
Normally this is implemented, and [these tests](https://github.com/intellifactory/websharper/blob/master/tests/WebSharper.Web.Tests/ClientSideJson.fs#L117-L133) are successful. Is it not working for you? Can you post a failing snippet?

**Comment by FilippoPolo** [comment]
Yup, error on my side. Sorry!
