### ISSUE TITLE
Embedded resources are not extracted

### ISSUE THREAD

**Issue by juselius** [intellifactory/websharper#517]
According to the documentation, referencing (assembly) embedded resources in  BaseResource() should automatically extract the resource file(s) into `Scripts/...` and `Content/...` respectively. This does not seem to happen, although the assembly is verified to contain the resource files, and the `src` and `href`  links are correctly generated in the template outputs.

Another problem is that url:s to non-embedded resources, with an absolute path (e.g.  `BaseResource("/css/custom.css")`, are not translated to the right sub-path when published. For example, publishing a site under `http://asdf.xyz/foo/` yields a resource url of `http://asdf.xyz/css/custom.css` instead of `http://asdf.xyz/foo/css/custom.css`.

I'm using WebSharper 3.6.6.225 and UI.Next 3.6.5.201.

**Comment by Tarmil** [comment]
Indeed, there is something missing in the documentation. You need to add the following attribute:

```fsharp
[<assembly:System.Web.UI.WebResource("myfile.css", "text/css")>]
do ()
```

The reason we don't extract files unless such an attribute exists is that you might want to embed files in your assembly for other reasons than serving them, and in this case extracting them is a potential security issue (you might have sensitive information in that file).

**Comment by juselius** [comment]
Ah, thank you! I actually stumbled upon the solution while studying the new UI.Next.Formlet library. I haven't tested yet on my on project(s) because I have been to busy with other things.

**Comment by Tarmil** [comment]
This has been added to [the documentation page](http://websharper.com/docs/resources).
