### ISSUE TITLE
WebSharper.CodeMirror 3.6.7.299/3.6.6.298  require inexistent versions of WebSharper

### ISSUE THREAD

**Issue by ca-ta** [intellifactory/websharper#525]
Hi guys, there seems to be something amiss with the WebSharper dependencies.
Paket has trouble resolving dependencies:
 - Paket reports that: 
   - WebSharper.CodeMirror 3.6.7.299 requires WebSharper 3.6.9.229
   - WebSharper.CodeMirror 3.6.6.298 requires WebSharper 3.6.8.228
 - However, the latest available WebSharper seems to be 3.6.7.227

Questions:
 - Have the WebSharper.CodeMirror packages newer than 3.6.5.297 been published by mistake?
 - Should WebSharper 3.6.9.229 (and the other corresponding packages) have been published but haven't?

For now I am manually restricting WebSharper.CodeMirror versions to be < 3.6, but I wanted to let you know there may be an issue lurking in package management.
> Note that I did try to post this on the forums first, but posting repeatedly failed with "Oops... Something unexpected happened" (using Chrome - logging in does not work in IE 11). 

Thanks!

**Comment by granicz** [comment]
Just pulled the trigger on a public release, should be out there shortly.
Not sure what happened with fpish, restarted it, now seems better.

**Comment by ca-ta** [comment]
Thanks @granicz - the nuget package dependencies are OK now.
