### ISSUE TITLE
HTML attribute values are not properly encoded when rendering markup on server

### ISSUE THREAD

**Issue by MaxKot** [intellifactory/websharper#526]
HTML attribute values are currently not encoded when HTML markup is rendered on the server side in WebSharper.Html.Server. This makes application vulnerable to script injection attacks and it is also inconsistent with the client-side markup rendering, as well as text nodes rendering.

This issue is caused by HtmlWriter.WriteAttribute not encoding attribute values by default. Hence similar issues may be present in other server-side HTML rendering code.

I have created issue intellifactory/websharper.html#4 and a fix for the WebSharper.Html repository but I am not sure if this is the right repository to apply the fix to.

**Comment by Tarmil** [comment]
Fixed in intellifactory/websharper.html#4.
