### ISSUE TITLE
Exception passing a macro-ed function to a generic constructor in an [<Inline>] method

### ISSUE THREAD

**Issue by Tarmil** [intellifactory/websharper#552]
Example:

```fsharp
type C<'T>(f: 'T -> obj) =
    [<Inline>]
    static member M() = C(Json.Encode)

let x = C<int>.M()
```

throws the following at compile time:

```
error : Failed to resolve generics: Index was outside the bounds of the array.
```

The error is specifically with this combination of conditions: if I don't use a macro-ed function such as `Json.Encode`, or if I pass it to a normal method instead of a constructor, or if the class is not generic, or if the `[<Inline>]` method is not in `C`, then it works.

**Comment by Jand42** [comment]
This was actually a more general error of not acquiring type parameter list of members correctly from FCS. Only resulted in an error when using the type resolving for inlines.
