### ISSUE TITLE
Extra information on "Abstract methods must be Instance" error

### ISSUE THREAD

**Issue by cgravill** [intellifactory/websharper#599]
I'm attempting to convert a library used with WebSharper 3.6.x to the 4.x beta. I've had some good progress but I'm getting some non-localised errors:

error : Abstract methods must be Instance

We only use "abstract" in a couple of places and extracting that code to a small sample doesn't yet reproduce the error. I've got the WebSharper.Compiler building but haven't managed to substitute in my WsFsc.exe yet.

Is there a detailed log anywhere? Could this message carry more information out e.g. similar messages give more context:

`printerrf "Abstract method not found in compilation: %s in %s" (string mDef.Value) td.Value.FullName`

**Comment by Jand42** [comment]
Thanks for the suggestion, added it, and made message a bit clearer. The final goal is to have name resolver errors localized too.

This error occurs whenever an abstract member has an inline or macro annotation, which is no longer allowed with WS4 forcing correct semantics on inheritance and overriding.

**Comment by cgravill** [comment]
Great, that'll be really helpful tracking down what's happening.

Thanks for the pointer about why it's happening. We don't have an [<Inline>] or macro on any of our methods explicitly marked as abstract so we must be doing it indirectly somehow.
