### ISSUE TITLE
Dictionary serialization issue with option types

### ISSUE THREAD

**Issue by FilippoPolo** [intellifactory/websharper#621]
Hi all,

I've found that dictionary serialization is not working on dictionary values that contain option types. When deserializing such an object, the values remain JSON-type objects, instead of becoming WebSharper objects. As such, they will be mostly unusable.

Here is a simple repro:

type testType = { foo: string option }
  let testOptionRoundTrip () =
    let t1:System.Collections.Generic.Dictionary<string,testType> = new System.Collections.Generic.Dictionary<string,testType>()
    t1.Add("foo", { foo = Some "foo" });
    t1.Add("bar", { foo = None });
    let t2:obj = WebSharper.Json.Encode t1 in
    let t3:System.Collections.Generic.Dictionary<string,testType> = WebSharper.Json.Decode t2 in
    let e1:testType = t1.["foo"] in
    let e3:testType = t3.["foo"] in
    let success = (e1 = e3) in
    if not success then
      sprintf "Round trip serialization/deserialization failed! Before: %s; after: %s" (Json.Stringify e1) (Json.Stringify e3)
        |> WebSharper.JavaScript.Console.Error;
    ()

This fails with:

>Round trip serialization/deserialization failed! Before: {"foo":{"$":1,"$0":"foo"}}; after: {"foo":"foo"}

**Comment by FilippoPolo** [comment]
Forgot to mention that this bug exists as of the current Zefir release.

**Comment by Jand42** [comment]
Fixed in https://github.com/intellifactory/websharper/commit/4c27a4cef700295d08c9565d486c0aa0cde71aab
Release coming soon.
