### ISSUE TITLE
Client side function throws when it has a tuple as a parameter

### ISSUE THREAD

**Issue by Houndolon** [intellifactory/websharper#628]
In Zafir, if I have a

    [<JavaScript>]
    let clientSide tuple = //...

or

    [<JavaScript>]
    let clientSide (a, b) = //...

with a 

    let tuple = //...
    client <@ clientSide tuple @>

on the server side, the following exception is thrown:

    [Exception: Wrong format for InlineControl at C:\Users\hudson.IFBUDS02\Server\var\jobs\Zafir.UI.Next\workspace\WebSharper.UI.Next\Doc.fs: 347.58-347.79: expected global value or function access, got: Let (arg00@,
         TupleGet (ValueWithName (({Id = 1;
      Title = Line50 "Dota 2";
      ModeratorIds = [1; 1];},
     [{Id = 1;
       AccountId = 1;
       GameId = 1;
       Text = Text500 "Dota 2 post adfasdf";
       TimePosted = 1.1.2016. 0:00:00;}; {Id = 1002;
                                          AccountId = 1;
                                          GameId = 1;
                                          Text = Text500 "Another Dota 2";
                                          TimePosted = 1.1.2016. 0:00:00;}]),
                                  gameWithPosts), 0),
         Let (arg01@,
              TupleGet (ValueWithName (({Id = 1;
      Title = Line50 "Dota 2";
      ModeratorIds = [1; 1];},
     [{Id = 1;
       AccountId = 1;
       GameId = 1;
       Text = Text500 "Dota 2 post adfasdf";
       TimePosted = 1.1.2016. 0:00:00;}; {Id = 1002;
                                          AccountId = 1;
                                          GameId = 1;
                                          Text = Text500 "Another Dota 2";
                                          TimePosted = 1.1.2016. 0:00:00;}]),
                                       gameWithPosts), 1),
              Call (None, gameContent, [arg00@, arg01@])))]
       <StartupCode$WebSharper-Web>.-ctor@155-11.Invoke(String message) +33
       WebSharper.Web.FSharpInlineControl..ctor(FSharpExpr`1 elt) +731
       WebSharper.UI.Next.Doc.ClientSide(FSharpExpr`1 expr) +204
       TeamTavern.WebApp.page@38-9.Invoke(FSharpOption`1 _arg1) in D:\Solutions\TeamTavern\TeamTavern.WebApp\Game\Game.fs:41
       Microsoft.FSharp.Control.args@835-1.Invoke(a a) +63
       Microsoft.FSharp.Control.AsyncIAsyncResult`1.GetResult() +2094282
       Microsoft.FSharp.Control.AsBeginEndHelpers.endAction(IAsyncResult iar) +71
       <StartupCode$FSharp-Core>.AsBeginEnd@1923.Invoke(IAsyncResult iar) +42
       WebSharper.Sitelets.HttpHandler.System-Web-IHttpAsyncHandler-EndProcessRequest(IAsyncResult result) +13
       System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9765121
       System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

Sending a list of tuples works fine though.

**Comment by Jand42** [comment]
Hi, thanks for the report, indeed detupling creates some quotation forms that the `InlineControl` class which is behind the `clientSide` helper does not recognize yet. We will expand it for next beta release, coming soon.
