### ISSUE TITLE
F# inner generics

### ISSUE THREAD

**Issue by cata** [intellifactory/websharper#642]
WebSharper 4 fails to compile the following valid F# code, with  
*"Failed to resolve generic parameter: b, found: a"*:

```
    let span pred l =
        let rec loop l cont =
            match l with
            | [] -> ([],[])
            | x::[] when pred x -> (cont l, [])
            | x::xs when not (pred x) -> (cont [], l)
            | x::xs when pred x -> loop xs (fun rest -> cont (x::rest))
            | _ -> failwith "Unrecognized pattern"
        loop l id
```

**Comment by Jand42** [comment]
Thanks for the report. In your sample, you can remove inner generics by a type annotation `(cont: 'a list -> 'a list)`

Generally, compiler could be improved that inner generic type parameters do not give an error, only when a macro would need it (when translation depends on the type), and then give a better error to move the function to a top level `[<Inline>]` for proper generic use.

**Comment by cata** [comment]
Thanks for the fix!
Sorry for the belated response, I somehow missed your reply.
