### ISSUE TITLE
Defining property with getter and setter and name in strict mode

### ISSUE THREAD

**Issue by Jooseppi12** [intellifactory/websharper#657]
This:
```fsharp
type RN () =
    ...
    [<Name "X">]
    member this.RNValue 
        with get() = y
        and  set v = y <- v
```
will fail in strict mode if we have a test case like this:
```fsharp
    let o = RN()
    ...
    equal o.RNValue 1
    o.RNValue <- 2
    equal o.RNValue 2
```

**Comment by Tarmil** [comment]
The problem is not quite caused by strict mode, but it was revealed by it. The getter and setter are both compiled to the same name, and IE rejects object literal with the same field twice (other browsers are OK with it strangely enough).
