### ISSUE TITLE
Opt-out of dead-code elimination

### ISSUE THREAD

**Issue by cgravill** [intellifactory/websharper#683]
The new code optimisation in WebSharper 4.x is really promising, is there any documentation on how to influence it? I’m trying to convert our code over to WebSharper 4.x and some of our code is called in UI by external functions. By default, WebSharper will optimise them out which is awkward.
I’ve found I can create a fake `[<SPAEntryPoint>]` then list all the functions I will later call (and ignore them) e.g.

```fsharp
[<SPAEntryPoint>]
let Main () =
    //Ensure WebSharper exports these functions
    //Had to start doing this in the 4.x branch

    OtherEntryPoint.Main() |> ignore

    function1 |> ignore
    //many more lines
    function77 |> ignore

    printfn("Starting fake WebSharper entry point..")
```

that’s obviously a bit clunky, and fragile – if your optimiser gets smarter it might drop the whole lot!

Is there any way e.g. an attribute to mark a function as always exported?

Could we just disable the optimiser somehow? That would be a shame but at least we get everything.

If I use two entry points (multiple tools, with shared code), I get an error. Is there any alternative to mark a function as called but not the single entry point?

All of this is being done with Zafir.4.0.159.36-beta6

**Comment by Jand42** [comment]
We will discuss and expand features of dead-code elimination (currently always on for SPAs), possibly with a new attribute that includes a function (and all dependencies) like `SPAEntryPoint` (but not having the uniqueness constraint and not running on start).
Currently code dependencies are collected before pure expressions (like unused local functions) are optimized away, so your workaround will be working and we will not change this until there is a better solution in place for defining exports.

**Comment by Jand42** [comment]
The quickest helpful change here is adding a compiler flag and msbuild property for opting out of dead-code elimination in bundle projects, doing this

**Comment by cgravill** [comment]
Thanks, that sounds great as an intermediate step. We can handle the pretty large downloads in our tools and it's equivalent to what we have with WebSharper 3.x.

The multiple attributes sounds like a good full solution that we'd be happy to use - it's nice to avoid downloading and parsing dead code even as part of a big tool.

**Comment by Jand42** [comment]
Opt-out of DCE by using `<WebSharperDeadCodeElimination>False</WebSharperDeadCodeElimination>` in the project file with `Zafir.4.0.160.40-beta6`

**Comment by cgravill** [comment]
Just to confirm that this worked for us. It does leave a slightly strange empty entry point (to get JavaScript out) but that's not a big issue
```fsharp
[<SPAEntryPoint>]
    let Main () = ()
```

Thanks for this adjustment and other recent fixes, our master branch is now running WebSharper 4.x beta!
