### ISSUE TITLE
`WebSharper.Json` name collision from C#

### ISSUE THREAD

**Issue by Jand42** [intellifactory/websharper#715]
`WebSharper.Json` modules is currently unusable from C#, as the types are colliding. Either one could be renamed by adding `CompiledName` attribute or moving them to different namespaces.

**Comment by Jand42** [comment]
Unfortunately F# compiler ignores `CompiledName` on modules, so this was not fixed. New ticket at https://github.com/dotnet-websharper/core/issues/907

**Comment by granicz** [comment]
Please paste here the FCS ticket about that, so we don't lose sight of it, thanks.
