### ISSUE TITLE
Uncaught ReferenceError: <SomeNamespace> is not defined

### ISSUE THREAD

**Issue by amieres** [intellifactory/websharper#720]
Previously the generated file WebServer.js looked like this: 
```
20  Rop=Global.Rop;
21  Result=Rop&&Rop.Result;
```
Now line 20 is gone and code fails with this error
WebServer.js:21 Uncaught ReferenceError: Rop is not defined
    at WebServer.js:21
```
Because the namespace Rop in file Common.js was not included because it was not used.

**Comment by Jand42** [comment]
Thanks, duplicate of https://github.com/intellifactory/websharper/issues/719
Sorry for this, a new release with the fix is coming today
