### ISSUE TITLE
Unable to encode class to JSON?

### ISSUE THREAD

**Issue by FilippoPolo** [intellifactory/websharper#725]
Hi all,
I'm trying to convert an F# class to/from JSON, but I can't make it work. The documentation only refers to C# classes; in theory, it should be the same, but in practice I'm always getting a "type not supported" error. This is my test case, a minimal class with a read/write property:
```
[<System.SerializableAttribute>]
type test(str:string) =
  class
    let mutable _str = str
    member this.Str
        with get() = _str
        and set(value) = _str <- value
  end
let encodeTest (t:test) = WebSharper.Json.Encode<test> t
let decodeTest (t:obj) = WebSharper.Json.Decode<test> t
```
What am I doing wrong?

**Comment by Jand42** [comment]
A class with `Serializable` works through RPC calls, but there are no automatic logic yet to encode/decode it on the client side properly. We might consider adding it. Recommended way now is to have your data structures which you would like to store (for example in localStorage) in records/unions/arrays, and then use ` WebSharper.Json.Serialize`\`Deserialize`.

**Comment by FilippoPolo** [comment]
I see, so Encode/Decode don't work on classes? The documentation at https://developers.websharper.com/docs/server-side_web_development/json_api/heading-2 suggest that they should. Is the doc wrong? Or is it a C#-only feature?

**Comment by Jand42** [comment]
Sorry, the documentation is indeed misleading, de/serializing classes is currently only implemented on the server-side. Adding this now to client-side macro.

**Comment by Jand42** [comment]
Added support, releasing soon. `Serializable` attribute and a default constructor is only needed for server-side use, can be omitted for de/serializing on the client.

**Comment by FilippoPolo** [comment]
Great, thanks!
