### ISSUE TITLE
Fix JavaScript RegExp

### ISSUE THREAD

**Issue by Jooseppi12** [intellifactory/websharper#728]
There are various browsers that don't implement the newest EcmaScript standard, so the `replace`, `match`, `split` and `search` methods on a regex value are not working as expected in those browsers.

**Comment by granicz** [comment]
Just to clarify, the reason for a breaking change was updating the regex bindings to match the latest, unsupported standard. This should be fixed by reverting to using members on strings.

**Comment by Jand42** [comment]
@Jooseppi12 There is a `Warn` attribute added in [beta7](https://github.com/intellifactory/websharper/releases/tag/Zafir.4.0.169.70-beta7) with WIG support that could be used to annotate non-standard members. The original intent was that you can put it on proxy methods that does not behave exactly as in .NET bc of some reason, but it fits this use too better than `Deprecated`.
