### ISSUE TITLE
Wrong implementation of Equality of simple class instances

### ISSUE THREAD

**Issue by Martin521** [intellifactory/websharper#734]
A type
`type IB (i:int) = let mutable n = i`
should have reference equality (according to F# spec).
I.e. `IB(1)=IB(1)` must be false.
FSC correctly implements this.
Websharper (Zafir) does not, and implements, it seems, deep equality.
It took me a day to isolate this in my code.

**Comment by Jand42** [comment]
This was planned a long time ago https://github.com/intellifactory/websharper/issues/543
Since this is can be a breaking change, WebSharper had structural equality by default for a long time, we never prioritized it but might revisit.

**Comment by Martin521** [comment]
It is a change, but at the same time just a bug.
A quite time-consuming bug.
I have ported a mid-sized project to client-side. Most of it went very smoothly. Some functions missing, but that I could work around. I love Websharper.
But this bug took me a long time to find (in my case it was of course not a boxed int, but a more complex type).
