### ISSUE TITLE
`sprintf ""` causes a weird error.

### ISSUE THREAD

**Issue by FrankBro** [intellifactory/websharper#743]
In a module with `WebSharper.Pervasives.JavaScript`, if you have `sprintf ""` anywhere, it will cause this weird issue in a `.targets` file.

Error		The input sequence was empty.
Parameter name: source	{PROJECTNAME}	{PATH TO PROJECT}\packages\WebSharper.3.6.20.6\build\WebSharper.targets	

Using 
* IntelliFactory.Xml
* WebSharper v3.6.20.6
* WebSharper.Html v3.6.12.2

**Comment by granicz** [comment]
Wow, that sounds odd. Have you tried with the latest Zafir version?

**Comment by FrankBro** [comment]
I haven't played with WebSharper in a while so I'm not sure what Zafir is referring to. Is it the codename of version 4 which is in beta? Should I switch to that?

**Comment by Jand42** [comment]
@granicz Tested on http://try.websharper.com/new-fsharp, it is a printf macro bug that affects Zafir too. Although `sprintf ""` does not have much use, this can be annoying and should be quick to fix.
