### ISSUE TITLE
compiler not translating member (property) with set correctly if there is also a Stub member

### ISSUE THREAD

**Issue by AlexPeret** [intellifactory/websharper#747]
hi!

I'm getting the following error message (on Firefox) while loading JQueryUI Autocomplete widget:

> TypeError: conf.set_Source is not a function

_conf_ is an instance of AutocompleteConfiguration. The error message goes away if I comment the _conf.Source_ line in the snippet bellow:

```
let conf = new AutocompleteConfiguration()
let completef (r : AutocompleteRequest, f : array<AutocompleteItem> -> unit) =
    let suggestions = Services.FilterCities r.Term
    let x =
        suggestions
        |> List.map (fun (k,v) -> { Label = v; Value = string k })
        |> List.toArray
    f x
conf.Source <- Callback completef // <--- this throws the error
```

This is the generated code extracted from Firefox view-source:
```
...
,conf=new AutocompleteConfiguration.New(),conf.set_Source({
   $:3,
   $0:function($1)
   {
    return completef($1[0],$1[1]);
   }
  })
...
```

and this is the [JqueryUI](https://github.com/intellifactory/websharper.jqueryui/blob/master/WebSharper.JQueryUI/Autocomplete.fs) snippet, I believe is not being compiled correctly:
```
[<JavaScript>]
    member this.Source
        with set (s : AutocompleteSource) =
            match s with
            | Listing x -> this.source <- unbox x
            | Items x -> this.source <- unbox x
            | Url x -> this.source <- unbox x
            | Callback x -> setCallback x
```

If I'm understanding it correctly, the compiler is not translating the **member ... with set ...** to _set_Source_.

Version: Zafir 4.0.185.88-beta10

**Note**: I'm not sure if this issue belongs to here. Please, let me know if a need to move it to another repository.

Best regards,
Alex

**Comment by Jand42** [comment]
Thanks for the report, indeed a single `Stub` member was setting the whole class to `Stub` behavior which assumes no declared method bodies
