### ISSUE TITLE
Content folder isn’t updated

### ISSUE THREAD

**Issue by AndreiDegtiarev** [intellifactory/websharper#749]
Solution consist of two projects: library and test project. In the library project the css file included with Build Action  “EmbeddedResource” and it is declared as resource inherited from BaseResource. In the main project css resource is referenced via “require” attribute. After build the Content from main project is empty, but the css file is properly referenced in results html code. See [small project PropertyGrid](https://github.com/AndreiDegtiarev/WebSharper.Community.PropertyGrid) as example

**Comment by Jand42** [comment]
Hi,

you also need to add an assembly-level `WebResouce` attribute:

``` fsharp
[<assembly: System.Web.UI.WebResource("PropertyGridProj.css", "text/css")>]
do ()
```

This is a borrowed ASP.NET concept so that only specified embedded files are unpacked.

See [Resources docs](https://developers.websharper.com/docs/resources) for further details.

**Comment by AndreiDegtiarev** [comment]
Thank you very much András. After some trials and errors everything is working now as expected. On the other side I am not ASP.NET but desktop “deserter” and with this concept don’t familiar :-). The websharper documentation wasn’t really helpful. Probably for further "deserters" some documentation extensions would be helpful
Andrei
