### ISSUE TITLE
Compilation of tree-based recursive functions into a loop.

### ISSUE THREAD

**Issue by jack-williams** [intellifactory/websharper#751]
The JavaScript code generated for the  function ```size``` over type ```ExampleTree``` is incorrect.

- Occurs on Zafir.FSharp version 4.0.181.82-beta9

* Example F# Code
```fsharp
type ExampleTree = 
  | TLeaf of int
  | TNode of (ExampleTree * ExampleTree)
  | TLink of ExampleTree


let rec size (t : ExampleTree) : int Set =
  match t with
  | TLeaf(i) -> Set.empty
  | TNode(l,r) -> Set.union <| size l <| size r
  | TLink(i) -> size i
```
* Generated JavaScript for ```size```

```javascript
size=function(t)
 {
  var $1,$2,r,l,i;
  while(true)
   {
    if(t.$==1)
     {
      r=t.$0[1];
      l=t.$0[0];
      t=l;
     }
    else
     if(t.$==2)
      {
       i=t.$0;
       t=i;
      }
     else
      return new FSharpSet.New$1(null);
   }
 };
```

The compiler is trying to optimise the function into a loop. In the case for ```TNode```, where ```t.$ == 1```,
the function  discards the result from the recursive call to the right branch ```t.$0[1];```.  For some reason it seems to also completely remove the ```union``` during compilation.

**Comment by atadi96** [comment]
In the WebSharper `Set` proxy [source code](https://github.com/intellifactory/websharper/blob/master/src/stdlib/WebSharper.Collections/Set.fs) I can't see where `Set.union` is proxied, so maybe that's why it's removing the call completely. I'll go ahead and try to add the proxy now and see if that fixes it!

**Comment by jack-williams** [comment]
I don't think it's tied to ```Set.union```. The following happens with addition:

```fsharp
let rec size (t : ExampleTree) : int =
  match t with
  | TLeaf(i) -> i
  | TNode(l,r) -> size l + size r
  | TLink(i) -> size i
```

```javascript
size=function(t)
 {
  var r,l,i;
  while(true)
   if(t.$==1)
    {
     r=t.$0[1];
     l=t.$0[0];
     t=l;
    }
   else
    if(t.$==2)
     {
      i=t.$0;
      t=i;
     }
    else
     return t.$0;
 };
```

**Comment by Jand42** [comment]
@jack-williams Thanks for the report, it is indeed still a bug in tail recursion optimizer, it seems to focus in on the `size l` call and not recognize that it is not in tail position. Testing and fixing.

**Comment by jack-williams** [comment]
No problem, thanks for the quick responses @Jand42 @atadi96.
