### ISSUE TITLE
How to correctly tag paket file references for JS compilation?

### ISSUE THREAD

**Issue by o1lo01ol1o** [intellifactory/websharper#754]
We have a private repository that hosts some libraries we'd like to be able to use client side.  These are currently included in projects via a paket `File: MyModule.Fs` references for each necessary in the library.  How can we tell a project that these should be compiled to JS for some projects and CLR to others?  

For example, in a server side project, we have 
```
solution
--paket-files
----Foo.fs
----Bar.fs
--[project files]
```
and in a client-side project we have
```
solution
--paket-files
----Foo.fs
----Bar.fs
--[project files]
```

Both `Foo.fs` and `Bar.fs` define modules in the namespace `FooBar`.  A module in `Bar.fs`, `FooBar.Bar` refers to a module in `Foo.fs`, `FooBar.Foo`:  this leads WS to complain that `FooBar.Foo` is does not exist in the Javascript assembly.  

Is there a good way of working with shared exterior sources like this?

**Comment by Jand42** [comment]
Hello,

with WebSharper 4, you can use the `JavaScript` attribute on assembly-level:

```fsharp
[<assembly: JavaScript>]
do ()
```

And you can also opt-out of its effect with [<JavaScript false>] on a module/type/member.

I know this does not cover the case where you would like to combine outside files with and without JS translation in the same project, but if you can split your application at a certain point so that the assembly-level setting can be different, these should solve your problem.

**Comment by Jand42** [comment]
I am turning this into a proposal: there could be an extension of the assembly-level usage, so that single files can be annotated from anywhere in the project: `[<assembly: JavaScript "Foo.fs">]`

Would this be required for your use case, or the above is enough? Thanks.

**Comment by o1lo01ol1o** [comment]
The above might be sufficient for our needs, however, we're now running into another problem: We have two projects with assembly-level JS attribute and they both reference the same namespace.

  This appears to be throwing a static naming error on the javascript assembly as websharper is attempting to add the namespace to the assembly twice.

**Comment by Jand42** [comment]
Namespaces itself should not cause any key clash as they are not registered, only types. Are you sure there is no two classes with the exact same full name? Also, what does the error say, or if it's just a generic Dictionary exception, can you paste the stack trace? Thanks a lot!

**Comment by cgravill** [comment]
Assembly attributes for control should nicely clean up some of our code (wasn't aware it'd been implemented in 4.x). We have libraries that are used both on a cluster and in a web worker via WebSharper. To make this work we stub out the JavaScript attribute in many files. Being able to do this in a central file will keep the source files clean. If it can toggle on globally and tweak files off, or adjust the style direct/inline etc. that would be great.

**Comment by o1lo01ol1o** [comment]
@Jand42 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Static member name conflict at JavaScript address: 'Empty.Grph.Graph.AlgebraicGraphs'	Mobile.Main	FSC	1	
```
from the following type:
```fsharp
module Graph = 
    type Grph<'a> =
            | Empty
[...] 
```

**Comment by Jand42** [comment]
New feature added, will be released soon:
`JavaScript("MyFile.fs")` and `JavaScript("MyAssembly.MyType")` attributes can be used on assembly level to mark files/types for JavaScript translation from outside of the affected file.
File names are case sensitive and include no path (this can be changed possibly, based on discussion).

**Comment by Jand42** [comment]
The new features of the `JavaScript` attribute are available in the freshly released version: https://github.com/intellifactory/websharper/releases/tag/WebSharper.4.0.190.100-rc
