### ISSUE TITLE
Class constructor causes crash

### ISSUE THREAD

**Issue by FilippoPolo** [intellifactory/websharper#757]
This code:
```
type test_type (foo:string) =
  static let doStuff (a:string) = a+"."
  member x.foo = foo
let run_test_type () =
  let tt = new test_type ("foo")
  tt
```
After translation to JS, will cause a crash at runtime. The translated constructor is calling $cctor, which is undefined.

Tested on Zafir 4.0.187.90-beta10.

**Comment by Jand42** [comment]
This is a duplicate of #753, fix will be released soon.
