### ISSUE TITLE
int.CompareTo fails to compile: "No macro fallback found for 'WebSharper.MacroModule+NumericMacro'"

### ISSUE THREAD

**Issue by atadi96** [intellifactory/websharper#760]
This simple client-side code fails to compile with the error message `No macro fallback found for 'WebSharper.MacroModule+NumericMacro'` aimed at the `(3).CompareTo 5` part.
```fsharp
    [<JavaScript>]
    let Main =
        let difference = (3).CompareTo 5
        Console.Log difference
```
I know I could use `a - b` instead of `a.CompareTo b` but it makes the code look a lot less pretty.

**Comment by Jand42** [comment]
F# also has `compare 3 5` and it works. We should fix `CompareTo` too, thanks for the catch.
