### ISSUE TITLE
Failing to compile pattern match against interface.

### ISSUE THREAD

**Issue by atadi96** [intellifactory/websharper#761]
In the code below, I get an error `Failed to compile a type check for type 'Samples.HelloWorld+IFoo'` when pasting it into TryWebSharper. My guess is that WebSharper can not compile the interface pattern match.
```fsharp
[<JavaScript>]
module HelloWorld =
    type IFoo =
        abstract member Bar: int
        
    let measure (target: obj) =
        match target with //error on 'target'
        | :? IFoo as foo -> foo.Bar
        | _ -> 0
```
Are there any known workarounds for this? My original use-case would be to override `object.Equals` and implement `System.IComparable` for a type.

**Comment by Jand42** [comment]
There has been a short ticket about this https://github.com/intellifactory/websharper/issues/575

Current workaround is only to check member name, not absolutely guaranteed to be from this interface. but WS base proxies has a unique name for all interface members and default translated interface names contain the full name of the type (you can use `Name` attribute on an interface member to set it explicitly).

```fsharp
[<JavaScript>]
module HelloWorld =
    type IFoo =
        [<Name "IFoo_Bar">]
        abstract member Bar: int
        
    let measure (target: obj) =
        if JS.In "IFoo_Bar" target then (As<IFoo>target).Bar else 0
```

A simpler solution with not full guarantee would be to compile type checks to this automatically, not fully safe, but convenient, I think that is reasonable.

**Comment by atadi96** [comment]
Yes, I think compiling to the method name checks would be sufficient, with normal .NET naming conventions I don't think there's much chance of it not working, but the WS compiler could also give a warning about it.

The workaround seems applicable, too, at the moment. Thanks for the quick reply!

**Comment by Jand42** [comment]
Adding name check only for the shortest name. Because default naming for interface members are guaranteed to be unique, this feels ok to me, `Name` attribute is an optimization you have to be careful with to give a unique name within your projects.
