### ISSUE TITLE
Websharper 4.0 rc doesn't work on iPad2

### ISSUE THREAD

**Issue by AndreiDegtiarev** [intellifactory/websharper#762]
Only empty page appears. It was tested on a simple project:
https://github.com/AndreiDegtiarev/WebSharper.Community.PropertyGrid
[Demo link](https://andreidegtiarev.github.io/WebSharper.Community.PropertyGrid/)
On Beta 8 everything was ok

**Comment by Jand42** [comment]
Hi,

tested and it works on Safari on iPhone with latest iOS. I know that iPad2 has an earlier version. Can you attach a debugger (Safari 6 on a Mac) to see what the exact error is if any? Thanks.

**Comment by AndreiDegtiarev** [comment]
Hi,
Ufortunatelly I don't have access to Mac.

**Comment by AndreiDegtiarev** [comment]
Websharper 4.0 is working now

**Comment by Jand42** [comment]
@AndreiDegtiarev Thanks, good to hear.
My guess is that fix to #783 solved it, some older JS engines can be more stringent about strict mode so JS parsing used to fail. We have encountered the same problem on the snapshot taker on http://try.websharper.com/ which is also fixed now.
