### ISSUE TITLE
Helper for embedding WebSharper expressions into F# quotations

### ISSUE THREAD

**Issue by Jand42** [intellifactory/websharper#764]
WebSharper macros see the parameters as `WebSharper.Core.AST.Expression`s, but sometimes returning F# quotations would be easier. This needs some way to embed `WebSharper.Core.AST.Expression` values into an `FSharp.Quotation.Expr`.

**Comment by granicz** [comment]
Can you give examples for when this would be useful?

**Comment by Jand42** [comment]
This is a small change and I will use it in the C# test runner generator https://github.com/intellifactory/websharper/issues/765

If we add the opposite helper too (F# quotation as AST too), for example a call like this (used at https://github.com/intellifactory/websharper/blob/master/src/stdlib/WebSharper.Main/Macro.fs#L1295) `Call (None, NonGeneric stringTy, NonGeneric padLeft, [r; cInt w2])` could be written as `Quotation <@ %(EmbedAST<string> r).PadLeft(w2) @>` which is safer and does not need the extra lookups, making writing macros in F# much nicer.

**Comment by granicz** [comment]
Small changes are good, let's keep them nice and simple and close ASAP. Thanks.
