### ISSUE TITLE
Add .SetJS()

### ISSUE THREAD

**Issue by Tarmil** [intellifactory/websharper#782]
As a counterpart to `.GetJS()`, to have a full C# alternative to F#'s `?` / `?<-`. Although I'm not sure what's the best way to do it. `GetJS` has a param array to access nested fields, so the options I see for `SetJS` are:

* `void SetJS(object value, params string[] fields)` is as feature-complete and type-safe as `GetJS`, but has awkward parameter order.
* `void SetJS(string field, params object[] nestedFieldsAndValue)` allows a more natural parameter order, but drops typedness for nested field names.
* `void SetJS(string field, object value)` abandons the idea of a param array altogether.

**Comment by Jand42** [comment]
I prefer the third option. If you want to set on a nested path, you can do `GetJS` with multiple arguments, then a `SetJS`.
