### ISSUE TITLE
Persistent login only lasts for 30 minutes

### ISSUE THREAD

**Issue by Tarmil** [intellifactory/websharper#797]
That seems to be the default expiration for FormsAuthentication's auth cookie, which we use [here](https://github.com/intellifactory/websharper/blob/e40c42bfc5a80ba0b4ca5ec7ceda0dcb9a6898dd/src/sitelets/WebSharper.Web/RpcModule.fs#L62). We can just change the expiration date to far in the future (like the CSRF token).

Maybe we should also add an overload `LoginUser(string, DateTime)` to allow users to provide the expiration date they want?

**Comment by granicz** [comment]
More like with a `TimeSpan` value to be added to the current time.
