### ISSUE TITLE
Integrate the TypeScript compiler

### ISSUE THREAD

**Issue by Jand42** [intellifactory/websharper#810]
Current progress on `ts-output` branch needs compiling `Web` project twice to run tests, because TypeScript compilation happens before the `CoreCompile` step by default, so it is not picking up WebSharper output. It has to be reconfigured that running Build once is enough.

Possibly this will need WebSharper's MSBuild tasks outputting all the unpacked files as an output variable, to be picked up by an extra TypeScript compilation step added after that.

**Comment by Tarmil** [comment]
I am currently using the nuget package `Microsoft.TypeScript.MSBuild` to make sure that ts runs and does so before ws. Considering that it's only needed for some project types (presumably, Website, Bundle and Html, but not Library or Extension), should we make the `WebSharper.{FSharp|CSharp}` packages depend on it? Or should we have users add it explicitly? I think we can make it a dependency, it's not harmful if it's there and not used.

**Comment by Tarmil** [comment]
The `.targets` files are now set up to properly run the TypeScript compiler after WebSharper, both in C# and F#, for Bundle, Website and Html project types. I added the NuGet dependency on MS.TS.MSBuild.
