### ISSUE TITLE
Verify TS output during WS compilation

### ISSUE THREAD

**Issue by Jand42** [intellifactory/websharper#813]
File reference-based `.ts` output are currently translated for every assembly on build (these can be used in Sitelets projects). When introducing more TS features, especially stronger typing, `.ts` output can become broken. To catch errors at their source project, it would be useful to optionally run a TypeScript compilation straight from the WebSharper compiler (starting in parallel with writing resources into final assembly).

This can be either opt-in or opt-out, needs to be decided.

**Comment by Jand42** [comment]
Unsafe constructs and meta-programming (inlined JS code, macros and generators) can introduce code that cannot be guaranteed to be correctly type-check in TS within WebSharper easily (short of rewriting entire the TS type type checker in .NET). So an optional guarantee could be introduced when needed for libraries, because they are not immediately translated to JS (just in a web project that uses them).

**Comment by Tarmil** [comment]
That's an inherent risk from using such constructs, you can't trust such code without testing it anyway so I don't think we should add this level of complexity for this.

**Comment by Jand42** [comment]
Dropping this after internal discussion deciding against it.
