### ISSUE TITLE
FSC: error FS0243: Unrecognized option: '--preferreduilang'

### ISSUE THREAD

**Issue by cgravill** [intellifactory/websharper#817]
There appears to be a new compiler option which is breaking WebSharper as reported here: http://www.fpish.net/topic/Some/0/83366 however 15.4 is now fully released making this more widespread.

In places we've been able to workaround by downgrading to F# 4.0 but we have a shared projects where that's inconvenient. On my own machine I've manually altered my `Microsoft.FSharp.Targets` in `C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0` to remove this field.

Any news on a resolution? We're running with the latest WebSharper release 4.0.193.110

**Comment by cgravill** [comment]
Related on the other workaround of using FSharp.Compiler.Tools we're on a recent release of that too (4.1.27) which has this new option in its target file as well.

**Comment by Jand42** [comment]
@cgravill Thanks for the report, I am testing updating FCS or if the latest still can't handle it, removing it before passing the args to FCS. There will be a quick release fixing this.

**Comment by cgravill** [comment]
Thanks for the quick release!
