### ISSUE TITLE
[<CompiledName "...">] is ignored in generating HTML files from offline sitelets

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#82]
Ideally, in code like this we should see home.html and not index.html:
    
    #!F#
    module MySite =
    ...
       type Action = | [<CompiledName "home">] Index
    ...
       let MySitelet =
          Sitelet.Content "/index" Action.Index Pages.Index
    
    type MyWebsite() =
        interface IWebsite<MySite.Action> with
            member this.Sitelet = MySite.MySitelet
            member this.Actions = [MySite.Action.Index]
    
    [<assembly: WebsiteAttribute(typeof<MyWebsite>)>]
    do ()
    

----------------------------------------
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/82
- Originally reported by: [IntelliFactory](http://bitbucket.org/IntelliFactory)
- Originally created at: 2012-08-16T00:19:12.837

**Comment by Tarmil** [comment]
In this case the `Sitelet.Content` decides the file name, so there is no problem. `CompiledName` is correctly handled for `Sitelet.Infer` as well.
