### ISSUE TITLE
Add type casts for functions used as values

### ISSUE THREAD

**Issue by Jand42** [intellifactory/websharper#829]
A bit of a shortcoming of TS type checking is that here:

```typescript
function apply<T, U>(f: (a: T) => U, x: T): U {
  return f(x);
}

function id<T>(x: T): T { return x }

let a = 3
let b = apply(id, a)
let c = apply(x => id(x), a)
```
only `c` has type `number`, `b` is resolved to type `{}` which is something on which nothing is allowed.

Without re-introducing the lambda, a solution is to have functions used as values annotated with the resolved type at that point:

```typescript
let d = apply(<(x:number) => number>id, a)
```

**Comment by Tarmil** [comment]
Just to note: this would fix collection proxies that do stuff like `List.map List.ofArray ...`, such as `List.chunkBySize`, `List.splitInto`, `List.windowed`.
