### ISSUE TITLE
TypeScript: lazy object initialization (`as this`) incorrectly compiled

### ISSUE THREAD

**Issue by Tarmil** [intellifactory/websharper#841]
[This class](https://github.com/intellifactory/websharper/blob/a9410e08630dea396088d61f0b22679737aa9912/tests/WebSharper.Tests/Object.fs#L180)'s constructor is translated as follows:

```typescript
        constructor(){
          super();
          this["this"]=(contents)=>[contents];
          new Obj();
          this["this"][0]=this;
          this.init=1;
        }
```

First, the `"this"` field is set to a function instead of a value; then, a useless call to `new Obj()` is done. I'm not certain what the correct output is; is this `new Obj()` meant to be the base call? In that case, then `super()` should be in that position, but TS forbids putting code before it.

**Comment by Jand42** [comment]
Now erasing the lazy cell and just using calls to this. In the case of proper initialization, this produces much simpler output and runs the same. Introduces a slight semantics difference, where initialization checks would fail in .NET but will run in JS.

The test constructor above is now completely omitted as it is reduced to trivial.
