### ISSUE TITLE
CSRF security problem

### ISSUE THREAD

**Issue by StefanBelo** [intellifactory/websharper#844]
(Read more about this issue here: https://forums.websharper.com/topic/83633)

In WebSharper code you have got:

        | _ when Remoting.csrfProtect && not (explicitlyAcceptedOrigin.IsSome || checkCsrf()) ->
            Error (403, "Forbidden", "CSRF")

So when a request is made from the same origin, `checkCsrf()` is not executed, so they are correct that CSRF is not checked and you have got problem in your code.

Here they say:

https://stackoverflow.com/questions/5207160/what-is-a-csrf-token-what-is-its-importance-and-how-does-it-work

that Cross-Site Request Forgery is actually made by requesting from the same origin, read about trick how it is done.

So when `Remoting.csrfProtect` is true, what you set by default in code, you really should check CSRF, so:

    | _ when Remoting.csrfProtect && not (checkCsrf()) ->
        Error (403, "Forbidden", "CSRF")

**Comment by Tarmil** [comment]
I cannot find where in the page you linked they say that the CSRF attack is made by requesting from the same origin. You can read [here](https://www.owasp.org/index.php/Testing_for_CSRF_(OTG-SESS-005)) the OWASP recommendations for testing CSRF vulnerability, and it involves building an attacker page on a separate domain, from which the request to the target site is made.

**Comment by StefanBelo** [comment]
On Microsoft Internet Explorer and Edge, x-csrftoken is set in POST request, but not in Chrome browser.

**Comment by StefanBelo** [comment]
And this is really quite strange, as on my PC (left) x-csrftoken is missing, but not on my test VPS (right side of image)

http://bfexplorer.net/Content/images/CsrfProblem2Os.png

Security experts from betfair also say:

We analyzed the image shared by Stefan in http://bfexplorer.net/Content/images/CsrfProblem.png, and in it we can see a cookie and header defined. The request shown here is successful despite the wrong origin, because the two tokens match. However, we tested the application in multiple browsers, and we never see the x-csrftoken header. On our tests, the lack of this header was even breaking the application in Internet Explorer (not Edge), as IE doesn’t send an Origin header with the RPC calls, and there is no x-csrftoken to match to the cookie.

**Comment by StefanBelo** [comment]
Betfair experts say:

It is possible that the issue lies on the csrftoken cookie. As this cookie is set with the HTTPOnly flag, the javascript on the client application cannot read the cookie, and as such it cannot set the header, failing silently. Our tests show that by removing this flag on the csrftoken cookie only (it should not be removed from the authentication cookie), the header is successfully sent. We suggest trying this fix and see if it solves the header issue.

***
How to do what they suggest?

**Comment by StefanBelo** [comment]
I set following:

  <system.web>
    
    <compilation debug="true" targetFramework="4.7"/>
    <httpRuntime targetFramework="4.0"/>
    
    
    <httpCookies httpOnlyCookies="false" requireSSL="true" lockItem="true" />

    <authentication>
      <forms requireSSL="true" />
    </authentication>
  </system.web>

**Comment by StefanBelo** [comment]
It seems that above setting in IIS solved the problem in following web browsers:

Microsoft Internet Explorer
Microsoft Edge
Chrome
Yandex Browser

but not in:

Mozilla Firefox

Your csrf implementation in JavaScript code:

var csrf = document.cookie.replace(new RegExp('(?:(?:^|.*;)\\s*csrftoken\\s*\\=\\s*([^;]*).*$)|^.*$'), '$1');
    if (csrf) {
        xhr.setRequestHeader('x-csrftoken', csrf);
    }

depends on some settings, so what you do for Mozilla Firefox?

**Comment by StefanBelo** [comment]
So problem was in IIS setting. Mozilla Firefox works after deleting browser storage.

**Comment by abelbraaksma** [comment]
@StefanBelo, is it possible that this bug crawled back into existence? I've been trying to get this working in IE11 on Windows 7, but with Websharper, it keeps returning an HTTP 403.  It seems to come from the lines of code you mentioned above:

```f#
    | _ when Remoting.csrfProtect && not (explicitlyAcceptedOrigin.IsSome || checkCsrf()) ->
        Error (403, "Forbidden", "CSRF")
```

I set the web.config with this:

```xml
<httpCookies httpOnlyCookies="false" requireSSL="true" lockItem="true" />
```

but that had no effect. Note that:

* In Firefox, Chrome, Opera, iPhone, Safari etc, this works fine
* In IE 11 on Windows 10 it works fine
* Edge works fine
* Wrong in IE 11 on Windows 7 (and possibly Windows 8). 
* _It works correctly in IE 11 in InPrivate mode_
* I can clearly see that:
  * In InPrivate mode the x-csfrtoken HTTP header is sent with the XHR requests
  * In a normal window, that HTTP header is not sent
* The problem disappears if I remove the `iframe` around the page

**Comment by abelbraaksma** [comment]
Note, I presented a workaround on SO: https://stackoverflow.com/questions/50017916/ie11-does-not-set-x-cfrtoken-http-header-unless-with-an-inprivate-window-this.

Also, the website mentioned here is no longer exhibiting this behavior, since I applied the workaround.
